# Generated by Django 5.0.7 on 2024-11-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_reimbursement_status'),
        ('reimbursements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='reimbursement',
            index=models.Index(fields=['is_paid', 'last_notification_sent'], name='reimburseme_is_paid_ad18ce_idx'),
        ),
    ]
