# Generated by Django 5.0.7 on 2024-12-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0002_reimbursement_last_notification_sent_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reimbursement',
            name='reimburseme_is_paid_ad18ce_idx',
        ),
    ]
