# Generated by Django 5.0.7 on 2024-11-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='receipt',
        ),
        migrations.AlterField(
            model_name='expense',
            name='video',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
