# Generated by Django 5.0.7 on 2024-11-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expense_description_remove_expense_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='video_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='video_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='video_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='video',
            field=models.BinaryField(blank=True, max_length=2147483648, null=True),
        ),
    ]
