# Generated by Django 5.0.7 on 2024-11-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_video_filename_expense_video_mime_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='video_filename',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='video_mime_type',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='video_size',
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='expense_videos/'),
        ),
    ]
