# Generated by Django 5.0.7 on 2024-11-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_reimbursement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='reimbursement_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
