# Generated by Django 4.2.17 on 2024-12-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_reimbursement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
